# Generated by Django 4.2.7 on 2024-01-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_appointment_yourage_alter_contact_mphone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
