# Generated by Django 4.2.7 on 2024-01-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Doctor',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
